# Generated by Django 4.0.1 on 2022-01-30 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meals',
            old_name='describtion',
            new_name='description',
        ),
    ]
